# Generated by Django 6.0.2 on 2026-02-17 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', help_text='Title of the conversation (auto-generated or user-set)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(help_text='The user who owns this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chathistory',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='The conversation thread this message belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['conversation', 'timestamp'], name='chatbot_cha_convers_09b704_idx'),
        ),
    ]
