# Generated by Django 6.0 on 2026-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_chathistory_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Category (e.g., 'Admissions', 'Tuition')", max_length=100)),
                ('question', models.CharField(help_text='The question or topic', max_length=500)),
                ('answer', models.TextField(help_text='The official answer')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the location (e.g., 'Registrar')", max_length=255)),
                ('description', models.TextField(help_text='Detailed description and where to find it')),
                ('map_available', models.BooleanField(default=False, help_text='Is there a map for this location?')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full Name with title (e.g., 'Sr. Marie Rosanne Mallillin, SPC')", max_length=255)),
                ('position', models.CharField(help_text='Official Job Title', max_length=255)),
                ('office', models.CharField(help_text='Where is their office located?', max_length=255)),
            ],
        ),
    ]
