# Generated by Django 6.0 on 2026-02-24 13:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_faq_location_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Automatically generated vector embedding for semantic search', null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
