# Generated by Django 4.2.10 on 2026-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_faq_embedding_location_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], help_text='Student feedback on this response (thumbs up/down)', max_length=10, null=True),
        ),
    ]
