# Generated by Django 4.2.10 on 2026-04-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chathistory_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_type', models.CharField(choices=[('Financial', 'Financial'), ('Academic', 'Academic'), ('Enrollment', 'Enrollment'), ('Mental Health', 'Mental Health')], max_length=20)),
                ('urgency', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=15)),
                ('assigned_advisor', models.CharField(default='Unassigned', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='The student this need case is about', on_delete=django.db.models.deletion.CASCADE, related_name='student_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Need',
                'verbose_name_plural': 'Student Needs',
                'ordering': ['-created_at'],
            },
        ),
    ]
