# Generated by Django 4.2.10 on 2026-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_customuser_avatar_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, default=None, help_text='Student ID number (e.g., 2024-00001). Leave blank for admin/staff accounts.', max_length=20, null=True, unique=True),
        ),
    ]
